# Generated by Django 2.0 on 2018-12-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diocese', '0003_auto_20181209_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archdiocese',
            name='change_date',
            field=models.DateField(blank=True, null=True, verbose_name='date changed'),
        ),
        migrations.AlterField(
            model_name='archdiocese',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='date ended'),
        ),
        migrations.AlterField(
            model_name='diocese',
            name='change_date',
            field=models.DateField(blank=True, null=True, verbose_name='date changed'),
        ),
        migrations.AlterField(
            model_name='diocese',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='date ended'),
        ),
    ]
