# Generated by Django 2.0 on 2018-12-10 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diocese', '0004_auto_20181209_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archdiocese',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='archdiocese',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='diocese',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='diocese',
            name='end_date',
        ),
    ]
