# Generated by Django 2.0 on 2018-12-22 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diocese', '0007_auto_20181210_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchdioceseChurch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('lat', models.CharField(blank=True, max_length=200, null=True)),
                ('lon', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('establish_date', models.DateField(verbose_name='date established')),
                ('diocese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diocese.Archdiocese')),
            ],
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('lat', models.CharField(blank=True, max_length=200, null=True)),
                ('lon', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('establish_date', models.DateField(verbose_name='date established')),
                ('diocese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diocese.Diocese')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('archdiocese_church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diocese.ArchdioceseChurch')),
                ('diocese_church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diocese.Church')),
            ],
        ),
        migrations.CreateModel(
            name='Deacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('year_born', models.CharField(blank=True, max_length=4, null=True)),
                ('year_ordained', models.CharField(blank=True, max_length=4, null=True)),
                ('priest', models.BooleanField(default=True)),
                ('order_priest', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DioceseAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('archdiocese', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diocese.Archdiocese')),
                ('diocese', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diocese.Diocese')),
            ],
        ),
        migrations.CreateModel(
            name='Priest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('year_born', models.CharField(blank=True, max_length=4, null=True)),
                ('order_name', models.CharField(max_length=10)),
                ('order_priest', models.BooleanField(default=False)),
                ('offender', models.BooleanField(default=True)),
                ('year_ordained', models.CharField(blank=True, max_length=4, null=True)),
                ('notes', models.CharField(max_length=1000)),
                ('archdiocese', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diocese.Archdiocese')),
                ('diocese', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diocese.Diocese')),
            ],
        ),
    ]
