# Generated by Django 2.0 on 2018-12-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diocese', '0009_auto_20181222_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priest',
            name='year_ordained',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
