# Generated by Django 2.0 on 2019-01-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diocese', '0011_auto_20190101_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='county',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_family',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_founder',
            field=models.CharField(blank=True, max_length=230, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_founding_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='archdiocesechurch',
            unique_together={('name', 'city')},
        ),
        migrations.AlterUniqueTogether(
            name='church',
            unique_together={('name', 'city')},
        ),
    ]
