# Generated by Django 2.0 on 2019-01-05 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diocese', '0012_auto_20190102_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priest',
            name='order_name',
        ),
    ]
