# Generated by Django 2.0 on 2019-01-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diocese', '0014_auto_20190109_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archdiocesechurch',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='archdiocesechurch',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='archdiocesechurch',
            name='establish_date',
            field=models.DateField(blank=True, null=True, verbose_name='date established'),
        ),
        migrations.AlterField(
            model_name='archdiocesechurch',
            name='lat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='archdiocesechurch',
            name='lon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='archdiocesechurch',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='archdiocesechurch',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='archdiocesechurch',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='archdiocesechurch',
            unique_together={('name', 'city', 'state')},
        ),
        migrations.AlterUniqueTogether(
            name='church',
            unique_together={('name', 'city', 'state')},
        ),
        migrations.AlterUniqueTogether(
            name='priest',
            unique_together={('first_name', 'middle_name', 'last_name', 'year_ordained')},
        ),
    ]
