# Generated by Django 2.0 on 2019-01-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diocese', '0015_auto_20190127_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchassignment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='churchassignment',
            name='start_date',
        ),
        migrations.AddField(
            model_name='churchassignment',
            name='end_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='churchassignment',
            name='position',
            field=models.CharField(default='Pastor', max_length=30),
        ),
        migrations.AddField(
            model_name='churchassignment',
            name='start_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='city',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='church',
            name='county',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='establish_date',
            field=models.DateField(blank=True, null=True, verbose_name='date established'),
        ),
        migrations.AlterField(
            model_name='church',
            name='lat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='lon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='church',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='church',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
