# Generated by Django 2.0 on 2019-01-29 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diocese', '0016_auto_20190128_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchassignment',
            name='clergy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diocese.Priest'),
        ),
    ]
