# Generated by Django 2.0 on 2019-01-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diocese', '0017_churchassignment_clergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchassignment',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
