# Generated by Django 2.0 on 2019-02-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diocese', '0018_churchassignment_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priest',
            name='middle_name',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
